// Build the runtime bundle and publish the shared table next to it.
//
// One ESM bundle, no runtime dependencies: it is imported by the generated
// shims from <store>/runtime/<host>/<version>/index.js and must load under
// both Node >= 20 and Bun. The bundle and the table are committed so a Go
// build (and go:embed) never needs Node; `make runtime` reproduces them.
import { build } from "esbuild"
import { copyFile, mkdir, readFile } from "node:fs/promises"
import { fileURLToPath } from "node:url"
import path from "node:path"

const here = path.dirname(fileURLToPath(import.meta.url))
const repo = path.resolve(here, "..")
const outDir = path.join(repo, "pkg", "runtime")

await mkdir(path.join(outDir, "bundle"), { recursive: true })
await mkdir(path.join(outDir, "table"), { recursive: true })

const result = await build({
  entryPoints: [path.join(here, "src", "index.ts")],
  outfile: path.join(outDir, "bundle", "index.js"),
  bundle: true,
  format: "esm",
  // node keeps the node: builtins external; Bun implements them too, which is
  // what lets the same bundle load under both hosts.
  platform: "node",
  target: ["node20"],
  mainFields: ["module", "main"],
  banner: {
    js: "// Generated by `make runtime` from runtime/src — do not edit.",
  },
  logLevel: "info",
})

if (result.errors.length > 0) {
  process.exit(1)
}

// The table is the one source of truth for the Go side too: publish it
// byte-for-byte and let a Go test pin the two copies together.
await copyFile(path.join(here, "events.json"), path.join(outDir, "table", "events.json"))

const bundle = await readFile(path.join(outDir, "bundle", "index.js"))
process.stdout.write(`runtime bundle: ${bundle.length} bytes\n`)
