package runtime

import (
	"encoding/json"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
)

// ShimOptions describe one generated shim: the module a host loads, which
// hands the package's manifest and the consent hash to the versioned runtime.
type ShimOptions struct {
	Host           string // host id ("opencode", "kilo", "pi")
	Dialect        string // "v1", "v2" or "pi"
	Package        string // package id
	Version        string // package version
	RuntimeDir     string // absolute <store>/runtime/<host>/<ver>
	ManifestPath   string // absolute manifest file the runtime reads
	ManifestSHA256 string // sha256 of the manifest file, pinned so an edited record cannot pass
	Consent        string // D5 consent hash of the hooks
	LogPath        string // optional JSONL log of the runtime's decisions
}

// shimPrefix is the generated-file banner: a shim is a receipt artifact, never
// hand-edited.
const shimPrefix = "// verger runtime shim"

// RenderShim renders the module a host loads. It imports the versioned runtime
// and hands it the manifest; when that import fails — the store was pruned, the
// runtime directory was removed — the shim itself registers the minimal deny
// over the blocking hook keys of its dialect (DESIGN §4.6: the fallback has no
// imports of its own).
func RenderShim(opts ShimOptions, table Table) ([]byte, error) {
	for _, path := range []struct {
		name  string
		value string
	}{
		{"runtime dir", opts.RuntimeDir},
		{"manifest path", opts.ManifestPath},
	} {
		if _, err := cleanPath(path.value); err != nil {
			return nil, fmt.Errorf("%s: %w", path.name, err)
		}
	}

	if opts.Host == "" || opts.Package == "" {
		return nil, errors.New("runtime shim needs a host and a package")
	}

	// The manifest is the record of what the hooks are: a shim that does not
	// pin its digest would let anyone who can write the file re-point the
	// script digests and keep the approved hook list. Refuse to render one.
	if opts.ManifestSHA256 == "" {
		return nil, errors.New("runtime shim needs the manifest sha256")
	}

	switch opts.Dialect {
	case "v1", "v2":
		return renderPluginShim(opts, table)
	case "pi":
		return renderPiShim(opts, table)
	default:
		return nil, fmt.Errorf("runtime shim: unknown dialect %q", opts.Dialect)
	}
}

// renderPluginShim renders the OpenCode/Kilo shim: one default export that
// carries both plugin forms (v2 `setup`, v1 `server`), which is what lets the
// same module serve OpenCode 1.x, OpenCode 2.x and Kilo (DESIGN §4.6, D31).
func renderPluginShim(opts ShimOptions, table Table) ([]byte, error) {
	var b strings.Builder

	b.WriteString(shimPrefix)
	fmt.Fprintf(&b, " — %s@%s (%s, %s). Generated by verger; do not edit.\n", opts.Package, opts.Version, opts.Host, opts.Dialect)
	b.WriteString("const OPTIONS = ")
	b.WriteString(mustJSON(shimOptionsDoc(opts)))
	b.WriteString("\n")
	fmt.Fprintf(&b, "const RUNTIME = %s\n", mustJSON(BundlePath(opts.RuntimeDir)))

	v2Keys := table.BlockingKeys("v2")
	v1Keys := table.BlockingKeys("v1")

	b.WriteString(`
// The fallback has no imports of its own: it must work when the runtime
// cannot be imported at all.
const fail = () => {
  throw new Error("verger: runtime unavailable for ` + opts.Package + `")
}

const DENY = {
  id: ` + mustJSON(pluginID(opts.Package)) + `,
  async setup(ctx) {
    for (const key of ` + mustJSON(v2Keys) + `) {
      ctx?.tool?.hook?.(key, fail)
    }
  },
  async server() {
    const hooks = {}
    for (const key of ` + mustJSON(v1Keys) + `) {
      hooks[key] = fail
    }
    return hooks
  },
}

let plugin

try {
  const runtime = await import(RUNTIME)
  plugin = await runtime.load(OPTIONS)
} catch (err) {
  plugin = DENY
}

export default plugin
`)

	return []byte(b.String()), nil
}

// renderPiShim renders the Pi extension shim: Pi calls the default export with
// its ExtensionAPI, and the runtime is imported asynchronously so a broken
// runtime still registers the blocking deny.
func renderPiShim(opts ShimOptions, table Table) ([]byte, error) {
	var b strings.Builder

	b.WriteString(shimPrefix)
	fmt.Fprintf(&b, " — %s@%s (%s, %s). Generated by verger; do not edit.\n", opts.Package, opts.Version, opts.Host, opts.Dialect)
	b.WriteString("const OPTIONS = ")
	b.WriteString(mustJSON(shimOptionsDoc(opts)))
	b.WriteString("\n")
	fmt.Fprintf(&b, "const RUNTIME = %s\n", mustJSON(BundlePath(opts.RuntimeDir)))

	piKeys := table.BlockingKeys("pi")

	b.WriteString(`
// The fallback has no imports of its own: it must work when the runtime
// cannot be imported at all.
const fail = () => ({ block: true, reason: "verger: runtime unavailable for ` + opts.Package + `" })

export default function (pi) {
  import(RUNTIME)
    .then((runtime) => runtime.piExtension(OPTIONS)(pi))
    .catch(() => {
      for (const key of ` + mustJSON(piKeys) + `) {
        pi?.on?.(key, fail)
      }
    })
}
`)

	return []byte(b.String()), nil
}

// shimOptionsDoc is the options object the shim hands the runtime.
func shimOptionsDoc(opts ShimOptions) map[string]any {
	doc := map[string]any{
		"host":         opts.Host,
		"dialect":      opts.Dialect,
		"manifestPath": filepath.Clean(opts.ManifestPath),
		"manifestSha":  opts.ManifestSHA256,
		"consent":      opts.Consent,
	}

	if opts.LogPath != "" {
		doc["logPath"] = filepath.Clean(opts.LogPath)
	}

	return doc
}

// pluginID is the identifier the host sees for one package.
func pluginID(pkg string) string {
	return "verger." + strings.ReplaceAll(pkg, "/", ".")
}

// mustJSON renders one value as JSON for embedding in a shim; the values are
// strings and string slices, so encoding cannot fail.
func mustJSON(value any) string {
	data, err := json.Marshal(value)
	if err != nil {
		return `""`
	}

	return string(data)
}
